version: 0.1

default:
  deploy:
    parameters:
      stack_name: recipe-embedding-pipeline
      region: us-east-1
      capabilities: CAPABILITY_IAM
  build:
    parameters:
      use_container: false
