default:
  deploy:
    parameters:
      stack_name: recipe-picker-mcp
      resolve_s3: true
      s3_prefix: recipe-picker-mcp
      capabilities: CAPABILITY_IAM CAPABILITY_NAMED_IAM
      image_repositories: []
  global:
    parameters:
      region: us-east-1
version: 0.1
